# Generated by Django 5.1.6 on 2025-03-10 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_emailcode_updated_transactionmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmessage',
            name='fromUser',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emailcode',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 6, 40, 53, 691396)),
        ),
    ]
