# Generated by Django 5.1.6 on 2025-03-10 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_emailcode_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='wasSuccessful',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailcode',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 9, 0, 57, 891881)),
        ),
    ]
