# Generated by Django 5.1.6 on 2025-04-09 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_transaction_remark_alter_emailcode_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='isBuy',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emailcode',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 9, 22, 18, 13, 63343)),
        ),
    ]
